apiVersion: v1
kind: Service
metadata:
  name: anydesk-viewer-service
spec:
  type: NodePort
  selector:
    app: anydesk-viewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
